profiles: fix the compilation to return errors instead of exiting

diff --git a/profiles.d/kernel/profile b/profiles.d/kernel/profile
--- a/profiles.d/kernel/profile
+++ b/profiles.d/kernel/profile
@@ -15,6 +15,31 @@ source "$ezBenchDir/profiles.d/utils/common.sh"
 # $testsList             [WO]: List of tests that should be ran in this profile
 # $testExcludeList       [WO]: List of tests that should be excluded in this profile
 
+function __compile__() {
+    # Return error codes:
+    # 71: Compilation error
+    # 72: Deployment error
+
+    # Compile the kernel. If any question arises, the default choice will be taken
+    # This part assumes that you have a working .config already set up. You can generate it using make localmodconfig.
+    yes '
+     ' | make oldconfig || return 71
+    make -j8 || return 71
+    capture=$(sudo make modules_install)
+    echo "$capture"
+    kernel_id=$(echo "$capture" | grep DEPMOD | grep -o '[^ ]*$')
+
+    # Tweak this part for your distribution
+    sudo cp arch/x86_64/boot/bzImage /boot/vmlinuz-linux-intel || return 72
+    sudo mkinitcpio -k "$kernel_id" -g /boot/initramfs-linux-intel.img || return 72
+
+    # Force grub to boot on the non-distro kernel that we just compiled
+    #
+    # WARNING: Make sure that grub reverts to the distro's kernel if the
+    # computer crashes!
+    sudo grub-reboot 1 || return 72
+}
+
 function __default_make_and_deploy__() {
     # Return error codes:
     # 71: Compilation error
@@ -22,26 +47,12 @@ function __default_make_and_deploy__() {
 
     x_show_debug_info_start
 
-    # Compile the kernel. If any question arises, the default choice will be taken
-    # This part assumes that you have a working .config already set up. You can generate it using make localmodconfig.
-    yes '
-     ' | make oldconfig || exit 71
-    make -j8 || exit 71
-    capture=$(sudo make modules_install)
-    echo "$capture"
-    kernel_id=$(echo "$capture" | grep DEPMOD | grep -o '[^ ]*$')
-
-    # Tweak this part for your distribution
-    sudo cp arch/x86_64/boot/bzImage /boot/vmlinuz-linux-intel || exit 72
-    sudo mkinitcpio -k "$kernel_id" -g /boot/initramfs-linux-intel.img || exit 72
-
-    # Force grub to boot on the non-distro kernel that we just compiled
-    #
-    # WARNING: Make sure that grub reverts to the distro's kernel if the
-    # computer crashes!
-    sudo grub-reboot 1 || exit 72
+    __compile__
+    compile_error=$?
 
     x_show_debug_info_stop
+
+    [ "$compile_error" -ne 0 ] && return $compile_error
 
     # Here we go, reboot on the new kernel!
     sudo reboot
